# Generated by Django 5.2.7 on 2025-10-03 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_contact_blogs_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="likes",
        ),
        migrations.AddField(
            model_name="blogs",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_blogs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
