# Generated by Django 5.2.7 on 2025-10-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_blogs_likes_blogs_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="blogs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.blogs",
            ),
        ),
    ]
